### PR TITLE
Song Factory Additions

### PR DESCRIPTION
**Pull request by coderveda27**
Finished implementing the song factory. Based on our group discussions, I also made changes to the Song entity so that we can take artists as List of Strings rather than Artist objects.

### CODE REVIEW

**Comment by yoonie-jang** [comment]
Thank you for making the changes that we all discussed together, I hope that this decision turns out to be the best direction for our program.

**Comment by jackwiebe0** [comment]
I'm glad that artists is now a List of Strings because then we won't have to worry about any duplicate Artist object or Songs with multiple artists not being accounted for

**Review by lunazay — COMMENTED** [review]
I love the changes; the artist factory is coming along, I think omitting the artist object and just making it into a list of strings because it becomes a more practical implementation of the Artist object type

**Review by ashleychristen — APPROVED** [review]
u slayed this queen! thank u for finishing ur use case and completing ur todos! maybe something u can add is some java documentation! thank u for figuring out if we wanted to use an artist object or a list of strings for the artist of the song

**Pull request merged**
